"""empty message

Revision ID: 8cd2daceeef6
Revises: 79f008942a2a
Create Date: 2022-10-03 20:16:11.069373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd2daceeef6'
down_revision = '79f008942a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_pet', sa.Column('id_country', sa.Integer(), nullable=True))
    op.add_column('lost_pet', sa.Column('id_department', sa.Integer(), nullable=True))
    op.add_column('lost_pet', sa.Column('id_city', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_pet', 'id_city')
    op.drop_column('lost_pet', 'id_department')
    op.drop_column('lost_pet', 'id_country')
    # ### end Alembic commands ###
