"""empty message

Revision ID: a89f23eaed75
Revises: e107e0e66c28
Create Date: 2022-09-28 23:49:56.408878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a89f23eaed75'
down_revision = 'e107e0e66c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    op.drop_table('city')
    op.alter_column('country', 'country_name',
               existing_type=mysql.VARCHAR(collation='utf8_spanish2_ci', length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'country_name',
               existing_type=mysql.VARCHAR(collation='utf8_spanish2_ci', length=100),
               nullable=False)
    op.create_table('city',
    sa.Column('id_municipio', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('municipio', mysql.VARCHAR(collation='utf8_spanish2_ci', length=100), nullable=False),
    sa.Column('estado', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_departamento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departments.id_departamento'], name='city_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_municipio'),
    mysql_collate='utf8_spanish2_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('departments',
    sa.Column('id_departamento', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('departamento', mysql.VARCHAR(collation='utf8_spanish2_ci', length=100), nullable=False),
    sa.Column('id_pais', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['country.id_country'], name='departments_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_departamento'),
    mysql_collate='utf8_spanish2_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
