"""empty message

Revision ID: b048cfc50fca
Revises: d710bfb114e7
Create Date: 2022-10-08 08:47:39.978580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b048cfc50fca'
down_revision = 'd710bfb114e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_report',
    sa.Column('id_report', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('hour', sa.DateTime(), nullable=True),
    sa.Column('id_lost_pet', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lost_pet'], ['lost_pet.id_lost_pet'], ),
    sa.PrimaryKeyConstraint('id_report')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_report')
    # ### end Alembic commands ###
