"""empty message

Revision ID: bf5510475724
Revises: 94d27228e84d
Create Date: 2022-09-27 23:24:43.793249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5510475724'
down_revision = '94d27228e84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_pet', sa.Column('pet_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_pet', 'pet_name')
    # ### end Alembic commands ###
