"""empty message

Revision ID: bf63764f9d75
Revises: b048cfc50fca
Create Date: 2022-10-08 11:27:09.894021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf63764f9d75'
down_revision = 'b048cfc50fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_pet', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_pet', 'status')
    # ### end Alembic commands ###
