"""empty message

Revision ID: f2a97c2ead9d
Revises: 4700d88207a3
Create Date: 2022-10-01 18:59:50.767818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2a97c2ead9d'
down_revision = '4700d88207a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_departamento', table_name='city')
    op.create_foreign_key(None, 'city', 'department', ['id_department'], ['id_department'])
    op.drop_column('city', 'id_departament')
    op.alter_column('country', 'country_name',
               existing_type=mysql.VARCHAR(collation='utf8_spanish2_ci', length=100),
               nullable=True)
    op.add_column('department', sa.Column('id_department', sa.Integer(), nullable=False))
    op.add_column('department', sa.Column('department_name', sa.String(length=100), nullable=True))
    op.alter_column('department', 'id_country',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('id_pais', table_name='department')
    op.create_foreign_key(None, 'department', 'country', ['id_country'], ['id_country'])
    op.drop_column('department', 'id_departament')
    op.drop_column('department', 'departament_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('departament_name', mysql.VARCHAR(collation='utf8_spanish2_ci', length=100), nullable=False))
    op.add_column('department', sa.Column('id_departament', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_index('id_pais', 'department', ['id_country'], unique=False)
    op.alter_column('department', 'id_country',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('department', 'department_name')
    op.drop_column('department', 'id_department')
    op.alter_column('country', 'country_name',
               existing_type=mysql.VARCHAR(collation='utf8_spanish2_ci', length=100),
               nullable=False)
    op.add_column('city', sa.Column('id_departament', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_index('id_departamento', 'city', ['id_departament'], unique=False)
    # ### end Alembic commands ###
